### PR TITLE
Hopefully fix searching in mtl-tile-list

### PR DESCRIPTION
**Pull request by JanLukasGithub**
Change search URL parameter name from s to search.
For some reason this fixes searching, probably because the s parameter has a default use.

### CODE REVIEW

**Review by winnewoerp — COMMENTED** [review]
`?s=` is the default for a search in WP: [https://linieplus.de/?s=k%C3%B6ln](https://linieplus.de/?s=k%C3%B6ln), so it triggers the search results page to be called. `?search=` returns all blog posts, for some reason: [https://linieplus.de/?search=k%C3%B6ln](https://linieplus.de/?search=k%C3%B6ln). I propose to use something other than `s` (of course) and `search`, like for example [https://linieplus.de/?proposalsearch=k%C3%B6ln](https://linieplus.de/?proposalsearch=k%C3%B6ln).

**Comment by JanLukasGithub** [comment]
Yeah took me a while but I figured out the `?s=` myself. But I think `?search=` should work when this PR gets merged, as I implement that with this commit. For me locally it works at least

**Review by winnewoerp — APPROVED** [review]
OK, let's see...

**Comment by JanLukasGithub** [comment]
So for me the search does work, but it is a full text search instead of just the titles

**Comment by winnewoerp** [comment]
Of course, but I think full text is better if we don't offer a selection for where to search. I think it's great for now.

**Pull request merged**
